language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: G/UUKV9HLm+L6rPI8hO9b1O8vlOJPUHNYedRXFEg1TZdn+GcFolKqgeffDD1NmG8v9h6K/+iXT6xzUj7CX+7d7afyjhOCiuwHUAKZoXyw3xy1SQrRXB87nZ9bsve0wHijJVvAMBIItcVI4q/As9HZwEjX3oYWdHwWxAjucI0h1GQMuVUCKgnHkHVNjt8RSERyxSbipW1MkZOQj02OBy6ngse6G1a4uejJygTGbOC2qC0JDWepa6XqK89GkdD2655tQbsBaY+5I+NzYK0ppgpBLojmjL2hSMR1tjKVk60v0oG0L2SlgFj6xvJmwCPDd77XGq/0kKSPjsC01DJHKzlc389y7ULZMNhwmuebE3L0PRfERE7UcxJ3NCv3UKReA404b9DATw4JjgHo0ynUYCQ25GR0jEotMV5SKHyLHIOCC+HIXCpslS8yPMoltSyF3GN9ORHAhmjXV+RvbCVeKz701C2ncWsOfM5gGzkLx3f4Pwpnm+v1SgMyQdJU3jMBhK7Oc8twC6ErEjNcaih4SlihV2lSdoeg8Wonctt9YeaUm/aw9Tprc3OwfiKqILoA33v9xd5uZ7GaKE4NeDKGtKGsiyKK4dprBtwv38g/kXXktQn+TWQxfuj2VvTJyeCikTHSE5J9xsNSewDNyuuTO0fUpbtGybetyskfEsS0O/xqj8=
  - secure: frtYFhplBQxxeddEM9hHF5f9ZHoY+TeD3hKPiR/A5CNwl+RPQIbyaRc1kf2C4XRLsnvHkWaqmFy1cgRkvr0f9ZLwkC3MzMPOrI8tpcuRfaxuB4rGF+RY5G0ad3er5Uf/YT3/+rXANo1ZFICNTqhf48Iol+ZjeD6l+aesZ5ANiduBshZf4FQo5Ts1nWZKPZX4IQ60TuAXLOQkma7FDxmc51gknGFklUY91As5HwIg6LL/KhY7k+n2eo2nq9IUMMWQiJZdODNhW7ZPc6mIMLLCgV7Sh8VjfGbvcY3vpNvBrYAcpMYh/8oMzkM5PbbH6WHuF0gRYQDqgbaYP8SffDnbMKQGaN+SlOGpx1qimhb5mMRnTskPaz+vNVED1sYsMkilonxttmCuoVrXLdBMgeWPM1rZp6gdIthrxDdd2AO66axgsqHvXJPgQdplsE6iCCY7bLRhJaeD/eNrFp99rwQqj2MBOL1OVWRm1Be2Wr23R4IjvOfh0lXWEJJyZUPuphCaI3X51DlIpygr3XPVFyIJjZ/n6BbSci/N/s7WUJe01Enw7qlNQXOWpMXiQEtAjwgqGr/JM9TWkzEy8KiMPL3TLAdgqPB/q8XR0h0t1T5EJBlG4+sipVWJ/IdKWP4hkab7u9c+8lCARgqmX44utMo6XYl1Jxs4FwfVfFo72+RyJV8=
  - secure: aLNnzMvnleWOKDUcMSOp/oUo4vHbF95lGzT1Ej3K3zTPN5bo8VjJd4EjiyRcU6hvuSRnu6uYwdK/1wLa+Ms5KIyOGazChswi8wFCPOQWkpvuEapYVU+o6LGx2Kml9sRbST4r0AnIpyfZSVCwaMbdsXAqT17mnegHg+4wHjRvJApjClHjhWxR9hDCo6OGkBJzFQ3pJ2byvFOss8tl0EeSfuC3w+4UIeHmoWG1LkrfgxMD3cmBHmOn/JX4VGn3H1a7y8/cCKuhiB+EWD2Pj3lsOJTY/Wqn+0sdsbHPpdorFKZbKOwMIH/O802R0TSDRAbTEU41bMSUk2ozx+eGLvgDGEpi8xZd7nx+WkhF3d3H9U706hU1pTmH46PgM5I6RyRi9syBrh2A99zpvNQ8e0rCFm0wr8qcOFMCEEfL+6jFecYVYjNThOZuNWdt7wVsyjiapmZklxdBFXNr5hIa6FLxeXZ0At6jS1ygFbqulySTXL/NOCTOSA1ejv5Ko5wiJHT8nJaIHUr3OUhtbKlnwVgRZ3IxjkFBkhBnGtNp6SSEQ0UNui7I6W0k8znfRCOHAvMN0I8LrzxDjkPFuWbftPOtIE2YlsL5reyNz1crAVWYx1jFwlc4Ri9AVafFWb2rfctdRf5W5yNBFJKdcXgB0FdPfEBTUUkM1x3uMobKcID9fno=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: hniTDK0EQ0kh2/FbzcYR3Q0+QQbrnTqUzTW/OGiEez5gV7BbBCnzDoTjmXnouwRmuSBCjlFCv5vWlRp9q+NyXzuM8rewVnyjri2Qc+v9E6bVeFhpCnh+qaxVwclEcLK7YNyNQhFw7Kkc6UQS4Cx1exUFfV5BCEzelITIWbHA7zGazGPo0Xjdjw1Z4CGaY+2ktjaJ9Gq+XWvohoGwU9nbdm1Kz5HC1qJmrxFJRovtfF5IAkLhk4d5FWrBNEz15vD7Cxan5j81miyx/XMsBw4RovQaWkltNG0vYmC+3oJY6z3Tuof98OeQk1TDsWX0JOVl7C5HrYr2FlWwVxb9thJVSXpNovAv4Vba+W6kW3u8+vw9MDnTIMmUHpuZEwwLZodtA0fKWMbWkJYycgVjO6X1ELJvM9+1fRg15y+3SYTYPe1V35crmZiIKsrNuE98214/ADmcSJyCvZKU1sgpE+GRQxwNMK1uYX2koGjMhgKZaRmESNpc5HmxB9XEL+BWpfvgIahqWWdSsI6EgpZ198YAxL3vyRQL+LpU3L8MTi2Tnh+iM3ci/+CmEPWZHv4f3Yv7+enmBdvfNp5Gd8+/yiHB2IvhTEto8Sad5XFK0ovOJh+/MA+uNKa5rfwaeJRhGZCuw3VMyhZIaoQmdknAoYgs6W2kAAG26X2E2bJ16IXsrIs=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
