language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - ATOMIST_REPO_USER=travis-mvn-deploy
  - secure: Izdk072En3Js9JZxL0URJgm5huxnigzhivzCoFGbl3FWpHCpTYAw4vC4g/0TmSObjqyXhaJ/HQ5V6Ibl5AXhGvV1lqyIH/q2HcITwI2p+zNt9NTfYcFd5SxjouSDMG0xI/8k6IWp1aMNSnFajO28D5dpjBbmZvMxpxaAOie0fBNo1XtE0NOWDVJW/9ELgbEG5TUFfCJj8O5+0Oe0clRBjgAKT9lIYrHJyKWDuzmhIbAVBTDFPWLMKPGCP87fjsjsk5yA2PL4JxcyEHmVmgKCWpvJBvruxiPuUxrFf+EmKm/+84kRbFleiqdmobg3FcbEHX90ajBhPzuXSSkI5hL1EcYwDrUpFgXhLuq+gHKUZ8iM0MTMQk1zoC7STivzXeJhxmQWHMYbYH6qy6zk0oxtwVFi0iu4ntmBLzwNZ6sQ5aOHVYxpwSUlvXHSNyjHlTs4t06TaKP3Wi1nyDdyfxrJuEr/LJmuQLSrXFZMT90w/VFUFfAZ9c4l8JA9SmuIibyDIKZUbBXzmfSTr5WJS1de34PzIy9sHYc/Qzmtw78jXpcJAg5Taz388CNe75MGl4M3OkjU9GhC0QdbYWDBhH47OnbyR7IFCHQcWjDVvQpTwgJSWDmnTZNxbJGUt42hzovfSqkyIDAKFz+njjb0YaK8YiNk/QJEbrXsQKBEq600+0U=
  - secure: Md48gq4iuOgt/5MxPw3GHuBsPUgGVJbAa7esLLNfHq3VniVIVpWG9+E84K0dln7qtpDgK/UpUh5nYcOp3dONN2izpYKvy8pKrBmOtT4l5zFRV01v/35AAA/9D4l9k3T/iJlPc6/1TJ+PBHydbKgSJ4OYYkDwgLQL8M8P5kXSBut/c4O2eQbghvZp0QtclRR07iaHGdJUSRDB+6GJ0Fj0he4MFO5XZlVyDoB+T/Gc3rteZfAnnLChs4JGDlaoi7qmeiyQvMcH/7ksQjNoPnnQlsZi2ypsliGQaJ2R4EkadiYMbloAUqmH5rZ5oGSKM3WJposo9b3xu4C11mUM5OuOwGco/xxC3FlbbZartB2kAg/TPRHU+w1EiNWZmaZlt6Yk1qeYSX+L0l7JJW2noHDAKtiD6Nq1XtP9igMZlhoUbPrj4ELAnTMqHAdwfUoS8bDdCOH3amYBvEd5yPy2srjJPcK5TUGFzvaWSNM1fqtCD4/sOrklIdIO904yf3VMULgq2cdwPCP7OX5PVBi95LNVOM/aA4TN466O8TrgayJfBQaLMTUnWJqUhQHbCuVnFXDv1PnU4oqUM87HcUlsTaU6X82ouypcin6R3jmetes2UtJr00FSc8eMEhzkjEi0Wkkq4kqls30nWb/SSBtZ1C/z8a9lRiEOAsu0CgPxY3gfvhg=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: hniTDK0EQ0kh2/FbzcYR3Q0+QQbrnTqUzTW/OGiEez5gV7BbBCnzDoTjmXnouwRmuSBCjlFCv5vWlRp9q+NyXzuM8rewVnyjri2Qc+v9E6bVeFhpCnh+qaxVwclEcLK7YNyNQhFw7Kkc6UQS4Cx1exUFfV5BCEzelITIWbHA7zGazGPo0Xjdjw1Z4CGaY+2ktjaJ9Gq+XWvohoGwU9nbdm1Kz5HC1qJmrxFJRovtfF5IAkLhk4d5FWrBNEz15vD7Cxan5j81miyx/XMsBw4RovQaWkltNG0vYmC+3oJY6z3Tuof98OeQk1TDsWX0JOVl7C5HrYr2FlWwVxb9thJVSXpNovAv4Vba+W6kW3u8+vw9MDnTIMmUHpuZEwwLZodtA0fKWMbWkJYycgVjO6X1ELJvM9+1fRg15y+3SYTYPe1V35crmZiIKsrNuE98214/ADmcSJyCvZKU1sgpE+GRQxwNMK1uYX2koGjMhgKZaRmESNpc5HmxB9XEL+BWpfvgIahqWWdSsI6EgpZ198YAxL3vyRQL+LpU3L8MTi2Tnh+iM3ci/+CmEPWZHv4f3Yv7+enmBdvfNp5Gd8+/yiHB2IvhTEto8Sad5XFK0ovOJh+/MA+uNKa5rfwaeJRhGZCuw3VMyhZIaoQmdknAoYgs6W2kAAG26X2E2bJ16IXsrIs=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
